### PR TITLE
Updated packages and fixed breaking changes.

### PR DESCRIPTION
**Pull request by strikefvela**
Updated packages to the latest versions and fixed breaking changes.

### CODE REVIEW

**Comment by surjithctly** [comment]
Thank you for this PR.

Any reason you used const function instead of normal one?

**Comment by surjithctly** [comment]
Also check the Nav & footer menu in mobile. Looks broken in this deployment preview

**Comment by strikefvela** [comment]
I used the const as it's just preference due to readibility, but I can change it back at your discretion.

I fixed the navbar and footer issues, they were being caused by the refactor of the links and the use of spans so I removed them. Also fixed an issue with the widget in dark mode and refactored the tailwinds config.

**Comment by surjithctly** [comment]
Merged. Thank you!

**Pull request merged**
