### PR TITLE
Update template to use next 14 and app router

### PR DESCRIPTION
**Pull request by PaulBratslavsky**
Ready for review.

### CODE REVIEW

**Review by surjithctly — CHANGES_REQUESTED** [review]
Hey,

Thanks so much for your PR. Can you make sure the original design stay same? because I see  testimonials, footer etc are changed. Also the source code includes unwanted files like /utils. 

The Theme Toggle is also bit different and it doesn't appear sometimes. do you know why?

**Comment by PaulBratslavsky** [comment]
Will take a look. Thanks.

**Comment by PaulBratslavsky** [comment]
@surjithctly I made the changes that you asked for.  Let me know if there is anything else.

**Comment by surjithctly** [comment]
now the components have moved, the root folder is no more required right? Also remove `[StrapiImage.tsx]` from the components or any similar which are not in use. 

It is throwing build error.

Thanks so much for your work. I really appreciate it.

**Comment by PaulBratslavsky** [comment]
@surjithctly cool I removed the StrapiImage.tsx file since it is no longer being used. 

I typically like to keep the src folder and it is something that is set to "yes" by default when running `create-next-app` 

I ran 'yarn build' to test, everything worked.  Let me know if there is anything else. Thanks.

**Comment by surjithctly** [comment]
Thanks, I meant the `/components` folder, which is now in two places. one is root and one inside `/src`, so only one is needed right?

**Comment by PaulBratslavsky** [comment]
@surjithctly yes, thank you.  I used that folder as reference when refactoring.  Forgot to remove it.  Just update it and removed the unused components folder.  Thank you.

**Comment by surjithctly** [comment]
Thank you for your effort @PaulBratslavsky 

It's merged.

**Comment by PaulBratslavsky** [comment]
@surjithctly glad I can help.🙂

**Pull request merged**
