### PR TITLE
update dependencies and convert file to typescript

### PR DESCRIPTION
**Pull request by morelmiles**
This PR solves:
- Update the project's dependencies 
- Convert the entire project to Typescript

### CODE REVIEW

**Comment by surjithctly** [comment]
Thanks, could you check the build errors:

image

**Comment by morelmiles** [comment]
Hi @surjithctly 
Errors fixed.

**Review by surjithctly — CHANGES_REQUESTED** [review]
Can you make sure the actual error message is shown instead of "This field is required"? Because some fields like email will show different error based on what user types. So we can't give same error.

**Comment by jeremyrajan** [comment]
+1 for this PR to be merged :)

**Comment by surjithctly** [comment]
Waiting for the fix and I'll be deploying it.

**Comment by surjithctly** [comment]
Closed in favor of #10

**Pull request closed without merging**
